# PURL configuration for http://purl.obolibrary.org/obo/apollo_sv
# Note this is a mixture of pointers to releases on googlecode and development on github. Should be fixed..

idspace: APOLLO_SV
base_url: /obo/apollo_sv

products:
- apollo_sv.owl: https://raw.githubusercontent.com/ApolloDev/apollo-sv/master/src/ontology/apollo-sv.owl

term_browser: ontobee
example_terms:
- APOLLO_SV_00000219

entries:

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=APOLLO_SV&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/APOLLO_SV_00000219
    to: http://www.ontobee.org/browser/rdf.php?o=APOLLO_SV&iri=http://purl.obolibrary.org/obo/APOLLO_SV_00000219

# Releases

- exact: /3.0.1/apollo_sv.owl 
  replacement: https://raw.githubusercontent.com/ApolloDev/apollo-sv/v3.0.1/src/ontology/apollo-sv.owl

# Misc

- exact: /dev/apollo_sv.owl 
  replacement: https://raw.githubusercontent.com/ApolloDev/apollo-sv/master/src/ontology/apollo-sv.owl

- exact: /bfo2/apollo_sv.owl 
  replacement: https://raw.githubusercontent.com/ApolloDev/apollo-sv/bfo2/src/ontology/apollo-sv.owl
  
- exact: /4.1/apollo_sv.owl
  replacement: https://raw.githubusercontent.com/ApolloDev/apollo-sv/v4.1/src/ontology/apollo-sv.owl
  
- exact: /4.0.1/apollo_sv.owl
  replacement: https://raw.githubusercontent.com/ApolloDev/apollo-sv/v4.0.1/src/ontology/apollo-sv.owl
  
 - exact: /region_neutral_instances_and_classes.owl
  replacement: https://raw.githubusercontent.com/ufbmi/obc-ide-owl/master/obc-ide-indexing-instances-and-classes-region-neutral-punned-instances-and-classes.owl
 
  - exact: /instances-and-classes-continent-of-South-America.owl
  replacement: https://raw.githubusercontent.com/ufbmi/obc-ide-owl/master/obc-ide-indexing-instances-and-classes-continent-of-South-America.owl  
  
  - exact: /instances-and-classes-continent-of-North-America.owl
  replacement: https://raw.githubusercontent.com/ufbmi/obc-ide-owl/master/obc-ide-indexing-instances-and-classes-continent-of-North-America.owl  
  
  - exact: /instances-and-classes-continent-of-Europe.owl
  replacement: https://raw.githubusercontent.com/ufbmi/obc-ide-owl/master/obc-ide-indexing-instances-and-classes-continent-of-Europe.owl  

  - exact: /instances-and-classes-continent-of-Australia.owl
  replacement: https://raw.githubusercontent.com/ufbmi/obc-ide-owl/master/obc-ide-indexing-instances-and-classes-continent-of-Australia.owl
  
  - exact: /instances-and-classes-continent-of-Asia.owl
  replacement: https://raw.githubusercontent.com/ufbmi/obc-ide-owl/master/obc-ide-indexing-instances-and-classes-continent-of-Asia.owl
  
  - exact: /instances-and-classes-continent-of-Africa.owl
  replacement: https://raw.githubusercontent.com/ufbmi/obc-ide-owl/master/obc-ide-indexing-instances-and-classes-continent-of-Africa.owl
